### ISSUE TITLE
Button START A MESSAGING

### ISSUE THREAD

**Issue by AdityaPranataSIregar** [smilefam/SendBird-Xamarin#5]
I've got problem when I clicked Buton Start A messaging to list member , any warning said "An unhandled exception occured."

**Comment by sf-jacob-kim** [comment]
@AdityaPranataSIregar We updated the sample project to use the latest SDK, please download it again.

**Comment by AdityaPranataSIregar** [comment]
@sf-jacob-kim  OK , I tried again and SOLVED when I using your APP_ID , when I using my APP_ID keep on error , what should I do ? , whether there is a line of code that must be changed again ??

**Comment by AdityaPranataSIregar** [comment]
Thanks before  @sf-jacob-kim , I did Typo in a channel URL lol =D
